export const FETCH_SINGLE_ORDER = 'FETCH_SINGLE_ORDER';
export const FETCH_SINGLE_ORDER_SUCCESS = 'FETCH_SINGLE_ORDER_SUCCESS';
export const EMPTY_ORDER = 'EMPTY_ORDER';
export const EDIT_ORDER = 'EDIT_ORDER';
export const PAY_ORDER = 'PAY_ORDER';
export const EDIT_ORDER_SUCCESS = 'EDIT_ORDER_SUCCESS';
export const EDIT_ORDER_ERROR = 'EDIT_ORDER_ERROR';
export const EMPTY_ORDER_ERRORS = 'EMPTY_ORDER_ERRORS';