export const FETCH_ASSIGNED_ORDERS = 'FETCH_ASSIGNED_ORDERS';
export const FETCH_ASSIGNED_ORDERS_SUCCESS = 'FETCH_ASSIGNED_ORDERS_SUCCESS';
export const FETCH_ASSIGNED_ORDERS_ERROR = 'FETCH_ASSIGNED_ORDERS_ERROR';
export const CHANGE_ASSIGNED_ORDER_STATUS = 'CHANGE_ASSIGNED_ORDER_STATUS';
export const CHANGE_ASSIGNED_ORDER_STATUS_ERROR = 'CHANGE_ASSIGNED_ORDER_STATUS_ERROR';
export const CLEAR_ASSIGNED_ORDER_ACTION_ERRORS = 'CLEAR_ASSIGNED_ORDER_ACTION_ERRORS';
export const ADD_COMMENT = 'ADD_COMMENT';
export const CHANGE_ASSIGNEE = 'CHANGE_ASSIGNEE';
