export const FETCH_DECLARATIONS = 'FETCH_DECLARATIONS';
export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FETCH_PAYDESK_ITEMS_SUCCESS = 'FETCH_PAYDESK_ITEMS_SUCCESS';
export const FETCH_PAYDESK_ITEMS_ERROR = 'FETCH_PAYDESK_ITEMS_ERROR';