export const FETCH_ORDER_STATUSES = 'FETCH_ORDER_STATUSES';
export const FETCH_ASSIGNED_ORDER_STATUSES = 'FETCH_ASSIGNED_ORDER_STATUSES';
export const FETCH_DECLARATION_STATUSES = 'FETCH_DECLARATION_STATUSES';
export const FETCH_ORDER_STATUSES_SUCCESS = 'FETCH_ORDER_STATUSES_SUCCESS';
export const FETCH_ASSIGNED_ORDER_STATUSES_SUCCESS = 'FETCH_ASSIGNED_ORDER_STATUSES_SUCCESS';
export const FETCH_DECLARATION_STATUSES_SUCCESS = 'FETCH_DECLARATION_STATUSES_SUCCESS';