export const FETCH_QUEUE = 'FETCH_QUEUE';
export const FETCH_QUEUE_SUCCESS = 'FETCH_QUEUE_SUCCESS';
export const ADD_TO_QUEUE = 'ADD_TO_QUEUE';
export const MOVE_QUEUE_ITEM_TO_DONE = 'MOVE_QUEUE_ITEM_TO_DONE';
