export const FETCH_WAREHOUSE_ORDERS = 'FETCH_WAREHOUSE_ORDERS';
export const FETCH_WAREHOUSE_DECLARATIONS = 'FETCH_WAREHOUSE_DECLARATIONS';
export const FETCH_WAREHOUSE_ORDERS_SUCCESS = 'FETCH_WAREHOUSE_ORDERS_SUCCESS';
export const FETCH_WAREHOUSE_DECLARATIONS_SUCCESS = 'FETCH_WAREHOUSE_DECLARATIONS_SUCCESS';
export const FETCH_WAREHOUSE_ORDERS_ERROR = 'FETCH_WAREHOUSE_ORDERS_ERROR';
export const FETCH_WAREHOUSE_DECLARATIONS_ERROR = 'FETCH_WAREHOUSE_DECLARATIONS_ERROR';