export const FETCH_OPERATOR_PROFILE = 'FETCH_OPERATOR_PROFILE';
export const FETCH_OPERATOR_PROFILE_SUCCESS = 'FETCH_OPERATOR_PROFILE_SUCCESS';
export const FETCH_OPERATORS = 'FETCH_OPERATORS';
export const FETCH_OPERATORS_SUCCESS = 'FETCH_OPERATORS_SUCCESS';
