export const FETCH_USER_PROFILE = 'FETCH_USER_PROFILE';
export const FETCH_USER_PROFILE_SUCCESS = 'FETCH_USER_PROFILE_SUCCESS';
export const UPDATE_BALANCE = 'UPDATE_BALANCE';
export const UPDATE_BALANCE_SUCCESS = 'UPDATE_BALANCE_SUCCESS';
// export const BALANCE_ERROR_TRUE = 'BALANCE_ERROR_TRUE';
// export const BALANCE_ERROR_FALSE = 'BALANCE_ERROR_FALSE';