export const DECLARATIONS_LOADING_ON = 'DECLARATIONS_LOADING_ON';
export const DECLARATIONS_LOADING_OFF = 'DECLARATIONS_LOADING_OFF';
export const ORDERS_LOADING_ON = 'ORDERS_LOADING_ON';
export const ORDERS_LOADING_OFF = 'ORDERS_LOADING_OFF';
export const ASSIGNED_ORDERS_LOADING_ON = 'ASSIGNED_ORDERS_LOADING_ON';
export const ASSIGNED_ORDERS_LOADING_OFF = 'ASSIGNED_ORDERS_LOADING_OFF';
export const USER_LOADING_ON = 'USER_LOADING_ON';
export const USER_LOADING_OFF = 'USER_LOADING_OFF';